# Generated by Django 4.1.3 on 2022-11-30 23:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('status', models.CharField(choices=[('ativa', 'ativa'), ('rascunho', 'rascunho'), ('suspensa', 'suspensa')], max_length=13)),
                ('etapas', models.CharField(choices=[('não iniciada', 'não iniciada'), ('iniciada', 'iniciada'), ('finalizada', 'finalizada'), ('justificada', 'justificada'), ('atrasada', 'atrasada')], max_length=13)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('start_at', models.DateField(auto_now=True)),
                ('ends_at', models.DateField(default='9999-01-01')),
                ('update_at', models.DateField(auto_now=True)),
                ('obs', models.TextField(blank=True)),
                ('concluida', models.BooleanField(default=False)),
                ('concluida_at', models.DateField(blank=True)),
                ('adiada', models.BooleanField(default=False)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
